# Generated by Django 5.1.2 on 2024-10-22 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0003_channelscheduledmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channelscheduledmessage",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="channelscheduledmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="channelscheduledmessage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="channelscheduledmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="channelscheduledmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
