# Generated by Django 5.1.2 on 2024-10-22 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0004_alter_channelscheduledmessage_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channelscheduledmessage",
            old_name="group",
            new_name="channel",
        ),
    ]
