# Generated by Django 4.2 on 2024-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
