# Generated by Django 4.2 on 2024-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="private_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
