# Generated by Django 5.1.2 on 2024-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="device_token",
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
