# Generated by Django 5.1.2 on 2024-10-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_notificationpreference_device_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
