# Generated by Django 5.1.2 on 2024-11-05 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_notificationpreference_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="device_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="public_key",
        ),
    ]
