# Generated by Django 4.2 on 2024-10-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_is_online_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
