# Generated by Django 4.2 on 2024-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
