# Generated by Django 4.2 on 2024-10-15 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0002_group_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="participants",
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="group_members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
