# Generated by Django 4.2 on 2024-10-17 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0006_grouppermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppermission",
            name="user",
        ),
    ]
