# Generated by Django 4.2 on 2024-10-10 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
