# Generated by Django 4.2 on 2024-10-16 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_scheduledmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
